# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5aac0ec1fe03391d0c9ca7fcf620c94029ea171a0d89a86ac0486ce26c85bceb8f9c6fd2d11251f69b3b6ba9d553b72f4e2dcca4c1840380d5ed0a1c25af75

test:
  secret_key_base: 6173e33e4ffc47fab066e5260c6a6ea95851c3184996935f4e9160efe811fb220834ec97c2ce756df524ba563020a8e05429323fb2f34f2881dcfe2182bb858d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
